--- isle-fedora/Dockerfile	2021-08-11 08:44:36.000000000 -0400
+++ Dockerfile	2021-08-11 08:48:30.000000000 -0400
@@ -1,4 +1,4 @@
-FROM islandoracollabgroup/isle-tomcat:1.5.9
+FROM 840783682283.dkr.ecr.us-east-1.amazonaws.com/islandoracollabgroup/isle-tomcat:1.5.9 
 
 ## Dependencies
 RUN GEN_DEP_PACKS="mysql-client \
@@ -32,10 +32,14 @@
 ## Copy installation configuration files.
 COPY install_properties/ /
 
+ARG DB_ENDPOINT
+
 ## Fedora Installation with Drupalfilter
 # @see: Fedora https://github.com/fcrepo3/fcrepo/releases & Drupal-filter https://github.com/Islandora/islandora_drupal_filter/releases
 RUN mkdir -p $FEDORA_HOME /tmp/fedora &&\
     cd /tmp/fedora && \
+    sed -i -e '10s@\(//\)mysql\(\\:\)@\1\${DB_ENDPOINT}\2@' \
+        -e '28s@\(//\)mysql\(\\:\)@\1\${DB_ENDPOINT}\2@' /usr/local/install.properties && \
     curl -O -L "https://github.com/fcrepo3/fcrepo/releases/download/v3.8.1/fcrepo-installer-3.8.1.jar" && \
     java -jar fcrepo-installer-3.8.1.jar /usr/local/install.properties && \
     $CATALINA_HOME/bin/startup.sh && \
