--- isle-fedora/Dockerfile	2020-10-22 12:35:20.000000000 -0400
+++ temp-fsu-fedora/Dockerfile	2020-10-15 08:18:25.000000000 -0400
@@ -25,15 +25,20 @@
     ANT_HOME=/opt/ant \
     MAVEN_MAJOR=${MAVEN_MAJOR:-3} \
     MAVEN_VERSION=${MAVEN_VERSION:-3.6.3} \
-    ANT_VERSION=${ANT_VERSION:-1.10.8}
+    ANT_VERSION=${ANT_VERSION:-1.10.9}
 
 
 ## Copy installation configuration files.
 COPY install_properties/ /
 
+## DB_ENDPOINT ENV
+ARG DB_ENDPOINT
+
 ## Fedora Installation with Drupalfilter
 # @see: Fedora https://github.com/fcrepo3/fcrepo/releases & Drupal-filter https://github.com/Islandora/islandora_drupal_filter/releases
 RUN mkdir -p $FEDORA_HOME /tmp/fedora &&\
+    sed -i -e '10s@\(//\)mysql\(\\:\)@\1\${DB_ENDPOINT}\2@' \
+        -e '28s@\(//\)mysql\(\\:\)@\1\${DB_ENDPOINT}\2@' /usr/local/install.properties && \
     cd /tmp/fedora && \
     curl -O -L "https://github.com/fcrepo3/fcrepo/releases/download/v3.8.1/fcrepo-installer-3.8.1.jar" && \
     java -jar fcrepo-installer-3.8.1.jar /usr/local/install.properties && \
